### ISSUE TITLE
请问您是根据那篇文章进行复现的呢？

### ISSUE THREAD

**Issue by poppingcode** [Little-Linzi/cs_omp#1]
请问您是根据那篇文章进行复现的呢？ 或者您代码的思路是什么呢？ 
我想熟悉一下您的代码，谢谢辣

**Comment by poppingcode** [comment]
比如您在 cs_omp/sklearn_omp_example.py代码中的line109行#得到采样的N，求出这个N是什么原理呢?谢谢

**Comment by yylime** [comment]
这是自己参考MATLAB写的，采样Ｎ的得到是使用N = 时间序列长度除以最小的时间间隔
